import eslintComments from "@eslint-community/eslint-plugin-eslint-comments"
import js from "@eslint/js"
import rnxKit from "@rnx-kit/eslint-plugin"
import eslintConfigPrettier from "eslint-config-prettier/flat"
import boundaries from "eslint-plugin-boundaries"
import importXPlugin, { configs as importXConfigs } from "eslint-plugin-import-x"
import { configs as jsdocConfigs } from "eslint-plugin-jsdoc"
import n from "eslint-plugin-n"
import { configs as nodeDependenciesConfigs } from "eslint-plugin-node-dependencies"
import packageJson, { configs as packageJsonConfigs } from "eslint-plugin-package-json"
import secureCoding from "eslint-plugin-secure-coding"
import security from "eslint-plugin-security"
import toplevel from "eslint-plugin-toplevel"
import globals from "globals"
import tseslint from "typescript-eslint"
import requireStrykerRationale from "./eslint-rules/require-stryker-rationale.mjs"
import {
  NETWORK_CORE_MODULES,
  NETWORK_GLOBALS,
  NETWORK_THIRD_PARTY_PACKAGES,
  RESTRICTED_NAMED_IMPORTS,
} from "./scripts/security-network/network-surface.mjs"

// The eslint-plugin-security / eslint-plugin-secure-coding rule set applied to every one of this
// repository's own source layers. `src/**` and `checks/**` take it verbatim; `scripts/**` /
// `eslint-rules/**` override exactly one entry (`detect-non-literal-fs-filename` -> "off": those
// are one-shot local tooling scripts that build paths from `import.meta`/`process.cwd()`, never
// network input -- see that block's own comment). Single source of truth so the two scopes can
// only ever differ by an explicit override, not by drift.
const SECURITY_RULES = {
  ...secureCoding.configs.strict.rules,
  "secure-coding/detect-object-injection": "off",
  "security/detect-buffer-noassert": "error",
  "security/detect-child-process": "error",
  "security/detect-disable-mustache-escape": "error",
  "security/detect-eval-with-expression": "error",
  "security/detect-new-buffer": "error",
  "security/detect-no-csrf-before-method-override": "error",
  "security/detect-non-literal-fs-filename": "error",
  "security/detect-non-literal-regexp": "error",
  "security/detect-non-literal-require": "error",
  "security/detect-object-injection": "off",
  "security/detect-possible-timing-attacks": "error",
  "security/detect-pseudoRandomBytes": "error",
  "security/detect-unsafe-regex": "error",
  "security/detect-bidi-characters": "error",
}

/**
 * Scoped to this package's own source (src/, test/, checks/) plus root-level
 * scripts/config files. test/e2e/*\/fixtures/** are self-contained
 * throwaway consumer projects the package-acceptance test installs the
 * packed tarball into -- not source, not linted here.
 */
export default tseslint.config(
  {
    ignores: [
      "dist",
      "coverage",
      "node_modules",
      "**/node_modules",
      "test/e2e/*/fixtures",
      // examples/ is a self-contained npm workspace with its own package.json,
      // tsconfig, and ESLint/Prettier configs -- a demonstration consumer of the
      // published package (see examples/README.md), not this package's own source.
      // It carries its own toolchain and is never installed, built, or run by this
      // repo's CI or `npm run contract`. Linting it here would fail
      // `boundaries/no-unknown-files` (it fits no element model) for no benefit.
      "examples",
      // Stryker's own scratch workspace -- a full copy of the project tree
      // it mutates and runs tests against; never source, and its transient
      // presence/absence between runs shouldn't affect lint results.
      ".stryker-tmp",
      "reports",
      // Machine-generated by the api-contract check's own tooling
      // (api-extractor snapshots of src/'s public surface, see
      // scripts/api-contract/). baseline.* is intentionally committed (it's
      // the compatibility diffing target), current.* is regenerated every
      // run -- neither is hand-written source, and `eslint --fix` rewriting
      // baseline.* would corrupt the very snapshot compatibility diffing
      // depends on.
      ".repo-contract",
      // A static, zero-logic legacy-module-resolution compatibility shim
      // (see specs/decisions/0004-public-surface-stays-narrow-no-cli-experimental-presets.md,
      // which documents the `./presets` subpath export this shim supports) --
      // not TypeScript/source in any sense `boundaries`'s element model
      // applies to, and never hand-edited beyond its initial creation.
      "presets/package.json",
      // docs/ is the published static site (docs/index.html), not a
      // TypeScript/source layer this package's module-boundary model
      // (`boundaries/elements` below) covers -- its one plain-JS asset,
      // docs/script.js, runs in the browser against browser globals this
      // config never defines, and has no dependency edges for `boundaries`
      // to police either way.
      "docs/script.js",
    ],
  },
  {
    // eslint-plugin-boundaries enforces this repository's real module-
    // boundary invariants as ESLint diagnostics, not only via the separate
    // `architecture` check (.dependency-cruiser.cjs, scoped to `src/**`
    // only, run out-of-band by `npm run test:architecture`) -- a violation
    // is a red squiggle while typing, not something that surfaces only on
    // the next full verification run.
    //
    // Every element/file pattern below is deliberately written to cover the
    // *entire* surface every `files:` block in this config lints. Combined
    // with `boundaries/no-unknown-files` and `boundaries/no-unknown-
    // dependencies` below (both "error"), any new file -- or any import
    // target -- that doesn't fall under an existing pattern fails the lint
    // check immediately instead of silently going unclassified. That's what
    // keeps this coverage complete as the repository grows, not merely
    // accurate on the day it was written.
    //
    // Resolving the `../foo.js`-style specifiers this codebase uses
    // throughout (ESM imports of `.ts` sources via their compiled `.js`
    // extension) to their real `.ts` files needs a TypeScript-aware
    // resolver -- plain Node/ESLint resolution can't do it, and every
    // element/dependency classification below would silently degenerate to
    // "unresolvable" without one. `import/resolver: { typescript }` (from
    // eslint-import-resolver-typescript) is what makes that resolution
    // work; `eslint-plugin-boundaries` itself just consumes it.
    plugins: { boundaries },
    settings: {
      "boundaries/root-path": import.meta.dirname,
      "import/resolver": {
        typescript: { alwaysTryTypes: true },
      },
      "boundaries/elements": [
        // The layered src/ pipeline documented in
        // specs/architecture.md#module-boundaries and enforced today by
        // .dependency-cruiser.cjs, mirrored here.
        { type: "config", pattern: "src/config" },
        { type: "execution", pattern: "src/execution" },
        { type: "evidence", pattern: "src/evidence" },
        // Not named in specs/architecture.md's module-boundaries diagram or
        // in .dependency-cruiser.cjs, but real: src/parsing/ is a
        // foundational leaf -- only src/evidence/ consumes it, and it
        // depends on nothing but src/types.ts and src/errors.ts. Same shape
        // as src/config/, so it gets the same "must not depend on the
        // layers built on top of it" policy below.
        { type: "parsing", pattern: "src/parsing" },
        // Hand-vendored, pure-type Standard Schema interface
        // (specs/decisions/0012-hand-vendored-standard-schema-support-for-optional-output-validation.md)
        // -- the most foundational leaf of all: zero imports of its own,
        // consumed by src/types.ts, src/index.ts, and src/parsing.
        { type: "standard-schema", pattern: "src/standard-schema" },
        { type: "policy", pattern: "src/policy" },
        // src/presets/ (including src/presets/shared/) is production code
        // like every other layer above, but architecturally different: it's
        // a second, independent public barrel (src/presets/index.ts), not an
        // internal layer only reachable through src/index.ts -- see the
        // root-config policy below, which deliberately does NOT list
        // "presets" among the layers root-config must reach only through
        // src/index.ts.
        { type: "presets", pattern: "src/presets" },
        // checks/ (including checks/shared/), scripts/ (including its
        // api-contract/architecture/adr-governance subdirectories), and
        // eslint-rules/ are each one architectural unit -- none needs a
        // finer internal boundary than "the whole tree participates in the
        // policies below".
        { type: "checks", pattern: "checks" },
        { type: "scripts", pattern: "scripts" },
        { type: "eslint-rules", pattern: "eslint-rules" },
        { type: "test", pattern: "test" },
      ],
      "boundaries/files": [
        // src/index.ts, src/types.ts, src/errors.ts, src/run-repo-contract.ts
        // -- the four files living directly in src/ rather than in one of
        // the layer folders above. Classified by file category, not element
        // type: eslint-plugin-boundaries elements are always folder-based,
        // and these are standalone files.
        { category: "src-root", pattern: "src/*.ts" },
        // Every root-level tool config file this repository has today --
        // and, via the glob, any future `*.config.ts`/`*.config.mjs`
        // sibling added the same way, with no change needed here. package.json
        // joins them here too: it's linted now (see the package-json/
        // node-dependencies blocks below) and has no import statements of its
        // own for `boundaries/dependencies` to police either way, but
        // `boundaries/no-unknown-files` still requires every non-ignored file
        // to classify as *something*.
        {
          category: "root-config",
          pattern: [
            "*.config.ts",
            "*.config.mjs",
            ".dependency-cruiser.cjs",
            "eslint.config.js",
            "package.json",
          ],
        },
        // The one legitimate import of compiled output by source in this
        // repository: scripts/run-contract.mjs dogfoods the built package
        // (`precontract` runs `npm run build` first) rather than its
        // TypeScript source. dist/ itself is never linted (see `ignores`
        // above) -- this only classifies it as a known dependency target so
        // that one real edge doesn't trip `boundaries/no-unknown-
        // dependencies`.
        { category: "build-output", pattern: "dist/**" },
      ],
    },
    rules: {
      "boundaries/no-unknown-files": "error",
      "boundaries/no-unknown-dependencies": "error",
      "boundaries/dependencies": [
        "error",
        {
          default: "allow",
          policies: [
            {
              from: { element: { type: "execution" } },
              disallow: { to: { element: { types: { anyOf: ["evidence", "policy"] } } } },
              message:
                "src/execution must not import src/evidence or src/policy -- ADR 0001 requires execution and policy evaluation to stay strictly phased.",
            },
            {
              from: { element: { type: "config" } },
              disallow: {
                to: { element: { types: { anyOf: ["execution", "evidence", "policy"] } } },
              },
              message:
                "src/config is the most foundational layer and must not depend on execution, evidence, or policy.",
            },
            {
              from: { element: { type: "parsing" } },
              disallow: {
                to: {
                  element: { types: { anyOf: ["config", "execution", "evidence", "policy"] } },
                },
              },
              message:
                "src/parsing is a foundational leaf (see its element definition above) and must not depend on config, execution, evidence, or policy.",
            },
            {
              from: { element: { type: "standard-schema" } },
              disallow: {
                to: {
                  element: {
                    types: { anyOf: ["config", "execution", "evidence", "parsing", "policy"] },
                  },
                },
              },
              message:
                "src/standard-schema is a hand-vendored, dependency-free leaf (see its element definition above) and must not depend on config, execution, evidence, parsing, or policy.",
            },
            {
              from: { element: { type: "presets" } },
              disallow: {
                to: { element: { types: { anyOf: ["execution", "evidence", "policy"] } } },
              },
              message:
                "src/presets defines plain check configs (run + policy over already-parsed evidence) and must not depend on the runtime layers that consume them -- execution, evidence, or policy.",
            },
            {
              from: [
                {
                  element: {
                    types: {
                      anyOf: [
                        "config",
                        "execution",
                        "evidence",
                        "parsing",
                        "policy",
                        "presets",
                        "standard-schema",
                      ],
                    },
                  },
                },
                { file: { categories: "src-root" } },
              ],
              disallow: {
                to: {
                  element: { types: { anyOf: ["checks", "scripts", "eslint-rules", "test"] } },
                },
              },
              message:
                "src/ is production code; it must never depend on checks/, scripts/, eslint-rules/, or test/ (generalizes .dependency-cruiser.cjs's src-must-not-import-scripts rule to every non-src directory).",
            },
            {
              from: { file: { categories: "root-config" } },
              disallow: {
                to: {
                  element: {
                    types: {
                      anyOf: [
                        "config",
                        "execution",
                        "evidence",
                        "parsing",
                        "policy",
                        "standard-schema",
                      ],
                    },
                  },
                },
              },
              message:
                "Only src/index.ts -- this package's curated public barrel -- may be imported from outside src/; reach its internals through it, never directly (specs/architecture.md#module-boundaries).",
            },
            {
              from: [
                { element: { types: { anyOf: ["checks", "scripts", "eslint-rules"] } } },
                { file: { categories: "root-config" } },
              ],
              disallow: { to: { element: { type: "test" } } },
              message:
                "checks/, scripts/, eslint-rules/, and root config files are consumed by test/ (and by each other); none of them may depend on test/ itself.",
            },
            {
              from: { element: { type: "scripts" } },
              disallow: { to: { element: { type: "checks" } } },
              message:
                "scripts/ is lower-level tooling that checks/ builds on -- checks/ -> scripts/ is the only allowed direction between them.",
            },
            {
              // Mirrors the root-config policy above ("Only src/index.ts... may be imported from
              // outside src/") and .dependency-cruiser.cjs's own
              // checks-and-scripts-must-not-import-src-internals rule: checks/ and scripts/ are
              // equally outside src/, so they must reach it only through src/index.ts (or the two
              // public-ish surfaces already reachable directly -- the four src-root files and
              // src/presets/) rather than an internal layer directly.
              from: { element: { types: { anyOf: ["checks", "scripts"] } } },
              disallow: {
                to: {
                  element: {
                    types: {
                      anyOf: [
                        "config",
                        "execution",
                        "evidence",
                        "parsing",
                        "policy",
                        "standard-schema",
                      ],
                    },
                  },
                },
              },
              message:
                "checks/ and scripts/ must reach src/ only through src/index.ts (its curated public barrel), src/types.ts/src/errors.ts, or src/presets/ -- never an internal layer (config/execution/evidence/parsing/policy/standard-schema) directly (specs/architecture.md#module-boundaries).",
            },
          ],
        },
      ],
    },
  },
  // package.json itself, checked by two complementary plugins: package-json
  // (field validity/shape/ordering) and node-dependencies (dependency
  // version-range/semver hygiene). Both ship their own languageOptions
  // (a JSON-aware parser) as part of their exported flat configs, so those
  // configs are spread wholesale rather than hand-copying just `.rules` --
  // losing the parser would silently stop these from linting JSON at all.
  {
    ...packageJsonConfigs.recommended,
    files: ["package.json"],
  },
  {
    files: ["package.json"],
    plugins: { "package-json": packageJson },
    rules: packageJsonConfigs.stylistic.rules,
  },
  ...nodeDependenciesConfigs["flat/recommended"],
  // The original eslint-plugin-eslint-comments (last released 2021) calls
  // the removed `context.getSourceCode()` API and crashes outright under
  // ESLint 10 -- @eslint-community/eslint-plugin-eslint-comments is the
  // actively maintained successor (same rule set, same authors' org) used
  // here instead, registered under the shorter `eslint-comments/*` rule
  // namespace rather than its own default `@eslint-community/eslint-
  // comments/*` prefix. All 7 rules that aren't either a no-op without
  // configuration (`no-restricted-disable`, which needs an explicit
  // restricted-rules list this repo has no use for) or wholesale opinion
  // rather than hygiene (`no-use`, which forbids every disable comment
  // outright -- in tension with this repo's own established pattern of
  // precise, justified inline suppressions, e.g. `local/require-stryker-
  // rationale` above) are enabled at "error".
  {
    files: [
      "src/**/*.ts",
      "test/**/*.ts",
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "eslint.config.js",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    plugins: { "eslint-comments": eslintComments },
    rules: {
      "eslint-comments/disable-enable-pair": "error",
      "eslint-comments/no-aggregating-enable": "error",
      "eslint-comments/no-duplicate-disable": "error",
      "eslint-comments/no-unlimited-disable": "error",
      "eslint-comments/no-unused-disable": "error",
      "eslint-comments/no-unused-enable": "error",
      "eslint-comments/require-description": "error",
    },
  },
  {
    // TypeScript-parsed first-party sources: import-x's own `configs.typescript`
    // turns `import-x/named` off here (a type-checked TS build already
    // catches a bad named import, more precisely than syntactic analysis
    // can) and points its resolver at eslint-import-resolver-typescript --
    // the same resolver `boundaries` above already depends on to follow this
    // repo's `.js`-extension-importing-`.ts`-source convention.
    files: [
      "src/**/*.ts",
      "test/**/*.ts",
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    plugins: { "import-x": importXPlugin },
    settings: {
      ...importXConfigs.typescript.settings,
      "import-x/resolver": { typescript: { alwaysTryTypes: true } },
    },
    rules: {
      ...importXConfigs.recommended.rules,
      ...importXConfigs.typescript.rules,
      "import-x/no-named-as-default": "error",
      "import-x/no-named-as-default-member": "error",
      "import-x/no-duplicates": "error",
    },
  },
  {
    // fast-check's own documented usage is `import fc from "fast-check"`
    // followed by property access -- `fc.integer()`, `fc.property()`,
    // `fc.assert()`, etc. -- even though every one of those is *also* a
    // named export, which is exactly the ambiguous shape `no-named-as-
    // default-member` exists to flag elsewhere. Here it's not a mistaken
    // import, it's every property test in this suite following the
    // library's own convention, so the rule is turned off for this
    // directory alone rather than rewritten against upstream's own docs.
    files: ["test/property/**/*.ts"],
    plugins: { "import-x": importXPlugin },
    rules: {
      "import-x/no-named-as-default-member": "off",
    },
  },
  {
    // Plain ESM scripts import-x can resolve with plain Node resolution --
    // no TS build to defer to, so `import-x/named` stays on here.
    files: [
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "commitlint.config.mjs",
      "eslint.config.js",
    ],
    plugins: { "import-x": importXPlugin },
    rules: {
      ...importXConfigs.recommended.rules,
      "import-x/no-named-as-default": "error",
      "import-x/no-named-as-default-member": "error",
      "import-x/no-duplicates": "error",
    },
  },
  {
    // eslint-plugin-n's `flat/all` config (every rule it ships, all
    // "error") rather than `flat/recommended` -- Node-specific correctness
    // and forward-compat checks that apply equally to library source,
    // tests, and tooling scripts. `no-missing-import` is turned off:
    // eslint-plugin-n's resolver produces false positives on real, existing
    // files throughout this repo (e.g. checks/coverage.ts's relative import
    // of scripts/coverage-thresholds.mjs, and this package's own root
    // `package.json#exports` map -- which only curates the *published*
    // subpaths, not every internal relative import -- appears to leak into
    // how the resolver treats plain relative imports within the package).
    // import-x's own `no-unresolved` (see the import-x blocks above) covers
    // the same "does this import target actually exist" concern without
    // the false positives.
    files: [
      "src/**/*.ts",
      "test/**/*.ts",
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "eslint.config.js",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    ...n.configs["flat/all"],
    rules: {
      ...n.configs["flat/all"].rules,
      "n/no-missing-import": "off",
    },
  },
  {
    // `src/**` ships as real published source (package.json's `files` -- see the "src" entry's
    // own comment there) so a *runtime* devDependency import there would be a real defect
    // `no-unpublished-import` should keep catching. `ignoreTypeImport` narrows that to runtime
    // imports specifically: src/presets/shared/vitest-json-policy.ts:1's `import type ... from
    // "vitest/reporters"` is erased entirely by the TypeScript compiler (confirmed: `grep vitest
    // dist/presets.d.ts dist/presets.d.cts` -> 0 hits) and never becomes a real dependency on the
    // devDependency-only `vitest` package -- the same "type-only dependencies are not a problem"
    // exemption `.dependency-cruiser.cjs`'s own not-to-dev-dep rule already grants.
    files: ["src/**/*.ts"],
    rules: {
      "n/no-unpublished-import": ["error", { ignoreTypeImport: true }],
    },
  },
  {
    // `no-unsupported-features/node-builtins` checks real usages against
    // this package's own published `engines.node` floor (>=20.0.0) -- exactly
    // right for src/ and test/, which run under that floor, but not for
    // these files: none of them ship (package.json's `files` allowlist is
    // just dist/schemas/README/LICENSE), so their real runtime is whatever
    // Node the contributor's machine or CI job uses -- already newer than
    // 20.0.0 today (several devDependencies here already require Node 22+).
    files: [
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "eslint.config.js",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    plugins: { n },
    rules: {
      "n/no-unsupported-features/node-builtins": "off",
    },
  },
  {
    // Both flagged for the same reason: `composeSignals` in
    // src/execution/abort-signals.ts feature-detects `AbortSignal.any`
    // (`typeof AbortSignal.any === "function"`) specifically *because*
    // it's newer than this package's `engines.node >=20.0.0` floor, falling
    // back to a manual composition where it's absent -- see that file's own
    // doc comment. Its own test, spawn-check.test.ts's "disposes its
    // composed abort signal" test, and run-checks.test.ts's "disposes the
    // composed run signal..." test (all of which need the same fallback
    // forced to get an observable dispose() to assert on -- runChecks
    // composes hostAbortController's signal with a caller-supplied
    // options.signal the same way spawnCheck composes runSignal with its
    // own timeout signal) deliberately delete and restore `AbortSignal.any`
    // to exercise that branch. The rule can't see the guard, only the bare
    // `AbortSignal.any` syntax, and would otherwise flag the exact code this
    // package wrote to handle the version gap safely.
    files: [
      "src/execution/abort-signals.ts",
      "test/unit/execution/abort-signals.test.ts",
      "test/unit/execution/spawn-check.test.ts",
      "test/unit/execution/run-checks.test.ts",
    ],
    plugins: { n },
    rules: {
      "n/no-unsupported-features/node-builtins": "off",
    },
  },
  {
    // no-sync/no-process-exit/no-process-env, scoped off for CLI tooling
    // scripts and tests -- none of these rules' rationale (don't block an
    // event loop other work depends on; don't hard-exit code a caller might
    // want to catch and handle; don't read ambient env instead of explicit
    // config) applies to a one-shot script that IS the whole process for
    // the duration of a single `npm run` invocation, or to test setup/
    // teardown code. `no-process-exit` in particular is how
    // scripts/run-mutation.mjs and scripts/run-test-category.mjs propagate
    // a spawned child's real exit code from inside its `"exit"` event
    // callback -- not something `throw` can do from there.
    files: ["scripts/**/*.mjs", "scripts/**/*.ts", "test/**/*.ts"],
    plugins: { n },
    rules: {
      "n/no-sync": "off",
      "n/no-process-exit": "off",
      "n/no-process-env": "off",
    },
  },
  {
    // Security-focused static analysis (secure-coding's `strict` config --
    // its widest rule set -- plus eslint-plugin-security, whose own rules
    // all default to "warn" and are bumped to "error" here) scoped to
    // production and tooling code, not test/: tests for this repo's
    // execution layer deliberately construct the exact shapes (spawned
    // commands, dynamic regexes) these rules exist to catch, as fixtures
    // for asserting this package rejects or handles them safely, and
    // flagging that intent as if it were the vulnerability would be a false
    // positive on the very tests that prove the vulnerability is handled.
    //
    // `detect-object-injection` (both plugins' variant) is off everywhere:
    // every one of its ~30 hits across this repo is either a numeric array
    // index (`results[index]`, `argv[i + 1]`, `dependents[depIndex]` --
    // never string-keyed, so no `__proto__`/`constructor`-style prototype-
    // pollution vector exists) or a string key already validated to exist
    // moments earlier (`checks[checkId]` after `if (!check) throw`,
    // `total[metric]` iterating `Object.entries` of the very same object).
    // Both are the rule's own well-known false-positive category -- it
    // flags any computed member expression regardless of whether the key is
    // a `number` or an attacker-influenced `string` -- and this codebase
    // already carries its own extensive per-site invariant comments (search
    // `noUncheckedIndexedAccess` throughout) explaining exactly why each of
    // these reads is safe; duplicating that as ~30 near-identical disable
    // comments would be noise, not rigor.
    files: ["src/**/*.ts", "checks/**/*.ts"],
    plugins: { "secure-coding": secureCoding, security },
    rules: SECURITY_RULES,
  },
  {
    // Same rule set as the src/checks block above, except
    // `detect-non-literal-fs-filename` is also off: every hit under
    // scripts/ builds its path from `path.join(root, ...)` where `root`
    // comes from `import.meta.url` (this repo's own directory) or a
    // caller-supplied root threaded through internal function calls --
    // never from network/request input, which is the actual vulnerability
    // this rule exists to catch. These are one-shot local tooling scripts
    // (build the package, generate a schema, diff against a base branch),
    // not a service accepting untrusted filenames.
    files: ["scripts/**/*.ts", "scripts/**/*.mjs", "eslint-rules/**/*.mjs"],
    plugins: { "secure-coding": secureCoding, security },
    rules: {
      ...SECURITY_RULES,
      // One-shot local tooling: paths come from `import.meta`/`process.cwd()`, never network input.
      "security/detect-non-literal-fs-filename": "off",
    },
  },
  {
    // Development-time layer of the "no network calls" invariant (README's
    // Enterprise/locked-down-environments section, SECURITY.md) -- scoped to
    // src/**/*.ts only, the entire built/published surface (see
    // package.json's "files"/exports; checks/, scripts/, and test/ are
    // never shipped and are explicitly out of this guarantee's scope). This
    // is layer one of two independent mechanisms: layer two is
    // scripts/security-network/scan.ts, an AST-based scan run as its own
    // repo-contract check (see checks/security-network.ts) that does not
    // invoke ESLint and therefore still catches a violation even if this
    // configuration were ever silently weakened or an eslint-disable
    // comment suppressed it -- see specs/decisions/0007-no-network-surface.md
    // for the full threat model and rationale. Deliberately does NOT add a
    // suppression-governance policy override for these two rule names: the
    // "eslint" domain's existing default policy already requires
    // justification + alternatives + remediation + category +
    // verificationMethod for any rule with no specific entry
    // (scripts/suppression-governance/policy-config.ts), which is exactly
    // the "extremely obvious in code review, and why" bar this invariant
    // needs -- not an unconditional ban, since a preset that genuinely
    // needs network capability (e.g. a future health-check preset) should
    // remain possible, just never silent.
    files: ["src/**/*.ts"],
    rules: {
      "no-restricted-imports": [
        "error",
        {
          paths: [
            ...[...NETWORK_CORE_MODULES, ...NETWORK_THIRD_PARTY_PACKAGES].flatMap((name) => [
              {
                name,
                message: `"${name}" performs network I/O. repo-contract's src/ tree must never do so directly -- see SECURITY.md's network-free surface guarantee. A preset that genuinely needs this requires a fully justified disable-comments.json entry (scripts/suppression-governance/policy-config.ts's "eslint" default policy), not a silent import.`,
              },
              {
                name: `node:${name}`,
                message: `"node:${name}" performs network I/O. repo-contract's src/ tree must never do so directly -- see SECURITY.md's network-free surface guarantee. A preset that genuinely needs this requires a fully justified disable-comments.json entry (scripts/suppression-governance/policy-config.ts's "eslint" default policy), not a silent import.`,
              },
            ]),
            ...RESTRICTED_NAMED_IMPORTS.map(({ specifier, importedNames }) => ({
              name: specifier,
              importNames: importedNames,
              message: `Importing ${importedNames.join(", ")} from "${specifier}" can be used to synthesize a dynamic require() and load a network module by a computed string, bypassing this same rule's static specifier checks. repo-contract's src/ tree has never needed require()/createRequire anywhere -- see SECURITY.md's network-free surface guarantee.`,
            })),
          ],
        },
      ],
      "no-restricted-globals": [
        "error",
        ...NETWORK_GLOBALS.map((name) => ({
          name,
          message: `"${name}" performs network I/O. repo-contract's src/ tree must never do so directly -- see SECURITY.md's network-free surface guarantee. A preset that genuinely needs this requires a fully justified disable-comments.json entry (scripts/suppression-governance/policy-config.ts's "eslint" default policy), not a silent usage.`,
        })),
      ],
      // `no-restricted-globals` only matches a bare identifier reference (e.g. `fetch(...)`) --
      // it cannot see `globalThis.fetch(...)`, the same capability reached through a property
      // access instead of a variable reference. `no-restricted-properties` closes that gap; both
      // rules are needed to cover the same NETWORK_GLOBALS list. See
      // scripts/security-network/scan.ts's own `globalThis.<name>` handling for the AST-scan
      // layer's matching coverage.
      "no-restricted-properties": [
        "error",
        ...NETWORK_GLOBALS.map((name) => ({
          object: "globalThis",
          property: name,
          message: `"globalThis.${name}" performs network I/O. repo-contract's src/ tree must never do so directly -- see SECURITY.md's network-free surface guarantee. A preset that genuinely needs this requires a fully justified disable-comments.json entry (scripts/suppression-governance/policy-config.ts's "eslint" default policy), not a silent usage.`,
        })),
      ],
    },
  },
  {
    // @rnx-kit/eslint-plugin's own six rules, registered directly rather
    // than through its `recommended`/`strict` configs -- those bundle a
    // whole standalone React Native ESLint setup (@eslint/js,
    // typescript-eslint, and the @react-native plugin's
    // `platform-colors` rule), which would duplicate and fight the
    // type-aware typescript-eslint setup this config already has, for an
    // ecosystem (React Native) this Node CLI package has nothing to do
    // with.
    files: ["src/**/*.ts", "test/**/*.ts", "checks/**/*.ts", "scripts/**/*.ts"],
    plugins: { "@rnx-kit": rnxKit },
    rules: {
      "@rnx-kit/no-const-enum": "error",
      "@rnx-kit/no-export-all": "error",
      "@rnx-kit/no-foreach-with-captured-variables": "error",
      "@rnx-kit/no-unnecessary-arrays": "error",
      "@rnx-kit/restricted-asset-imports": "error",
    },
  },
  {
    // `type-definitions-only` requires every top-level statement in a file
    // to be a type declaration -- correct only for genuine ambient
    // declaration files, which in this repo means exactly the
    // hand-written *.d.mts siblings of scripts/**/*.mjs and
    // eslint-rules/**/*.mjs (see their own config block further down).
    files: ["scripts/**/*.d.mts", "eslint-rules/**/*.d.mts"],
    plugins: { "@rnx-kit": rnxKit },
    rules: {
      "@rnx-kit/type-definitions-only": "error",
    },
  },
  {
    // no-toplevel-var: safe everywhere first-party code runs -- it just
    // forbids a declaration keyword at module scope, regardless of whether
    // the module also has legitimate top-level side effects.
    files: [
      "src/**/*.ts",
      "test/**/*.ts",
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "eslint.config.js",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    plugins: { toplevel },
    rules: {
      "toplevel/no-toplevel-var": "error",
    },
  },
  {
    // no-toplevel-let, by contrast, excludes test/**/*.ts and
    // scripts/**/*.mjs: every test file's top-level fixture (`let root:
    // string`, assigned inside `beforeEach`/reassigned across tests) is the
    // standard Vitest setup/teardown idiom, not achievable with `const`
    // without restructuring the whole suite; the same goes for the
    // CLI scripts' `let` variables assigned inside a top-level `try` block
    // or accumulated across a loop (e.g. run-coverage.mjs's
    // `anyTestFailure`), a `const` genuinely cannot express either shape.
    files: [
      "src/**/*.ts",
      "checks/**/*.ts",
      "scripts/**/*.ts",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "eslint.config.js",
      "*.config.ts",
      "repo-contract.config.ts",
    ],
    plugins: { toplevel },
    rules: {
      "toplevel/no-toplevel-let": "error",
    },
  },
  {
    // no-toplevel-side-effect, by contrast, is scoped narrowly to src/,
    // checks/, and scripts/**/*.ts -- the layers where a bare top-level
    // statement would be a real import-time side effect. It's deliberately
    // left off of: test/**/*.ts, where every file's top-level
    // `describe(...)` call is the correct, idiomatic Vitest shape, not a
    // side effect to eliminate; scripts/**/*.mjs and eslint-rules/**/*.mjs,
    // which are executable entrypoints whose entire purpose is to run code
    // at the top level when invoked directly; and the root *.config.ts /
    // *.config.mjs files, which this rule already can't flag anyway since
    // their `export default someBuilder(...)` shape is an
    // ExportDefaultDeclaration, a node type this rule doesn't listen for.
    files: ["src/**/*.ts", "checks/**/*.ts", "scripts/**/*.ts"],
    ignores: [
      // These three are dual-purpose: an importable module of functions
      // (used directly by tests and by other scripts/checks) that's also
      // runnable as a standalone CLI entrypoint, gated by the standard
      // `if (process.argv[1] && import.meta.url === pathToFileURL(...))`
      // "only run main when executed directly, not when imported" guard --
      // a top-level `IfStatement`, which is exactly the shape this rule
      // exists to catch, but is the correct idiom here rather than a smell.
      "scripts/adr-governance/check.ts",
      "scripts/api-contract/check.ts",
      "scripts/api-contract/update-baseline.ts",
      "scripts/api-docs/check.ts",
      "scripts/api-docs/generate.ts",
      "scripts/security-network/scan.ts",
      "scripts/suppression-governance/check.ts",
    ],
    plugins: { toplevel },
    rules: {
      "toplevel/no-toplevel-side-effect": "error",
    },
  },
  {
    // jsdoc's TypeScript-flavored "error" preset: `no-types: error` bans
    // redundant type annotations inside JSDoc comments (this is a fully
    // typed TS codebase -- TS's own syntax is the single source of truth
    // for types, never a duplicate `{string}`-style JSDoc annotation) while
    // still requiring/validating the rest of JSDoc's structural contract
    // (params, descriptions, etc. line up with the real signature).
    ...jsdocConfigs["flat/recommended-typescript-error"],
    files: ["src/**/*.ts", "checks/**/*.ts", "scripts/**/*.ts"],
  },
  {
    files: ["src/**/*.ts", "test/**/*.ts"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      // Encodes "this package executes what it's told, never interprets
      // output as code" as something CI enforces, not just documents -- see
      // SECURITY.md.
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",
      // TypeScript's own compiler already catches genuinely undefined
      // identifiers, more accurately than this base rule.
      "no-undef": "off",
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    files: ["test/**/*.ts"],
    rules: {
      "@typescript-eslint/no-non-null-assertion": "off",
      "@typescript-eslint/require-await": "off",
    },
  },
  {
    // `// Stryker disable` directives are only meaningful where
    // stryker.config.mjs actually mutates (`src/**/*.ts`) -- scoped
    // separately from the shared src+test block above so that scope is
    // explicit rather than incidental.
    files: ["src/**/*.ts"],
    plugins: { local: { rules: { "require-stryker-rationale": requireStrykerRationale } } },
    rules: {
      "local/require-stryker-rationale": "error",
    },
  },
  {
    // scripts/api-contract/*.ts is real, substantial logic (unlike the thin
    // scripts/*.mjs wrapper scripts below) and gets the same type-aware
    // strict linting src/ does.
    files: ["scripts/**/*.ts"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    // stryker.config.mjs, commitlint.config.mjs and eslint.config.js are
    // root-level, plain-ESM config files with the exact same linting needs
    // as scripts/**/*.mjs below (no type-aware rules, just recommended JS
    // rules against Node/ESM), so they share this block rather than getting
    // one each.
    files: [
      "scripts/**/*.mjs",
      "eslint-rules/**/*.mjs",
      "stryker.config.mjs",
      "commitlint.config.mjs",
      "eslint.config.js",
    ],
    extends: [js.configs.recommended],
    languageOptions: {
      parserOptions: { sourceType: "module" },
      globals: globals.node,
    },
  },
  {
    // dependency-cruiser loads this as CommonJS regardless of this
    // package's own `"type": "module"` -- the `.cjs` extension is load-
    // bearing, not incidental, so this gets its own sourceType rather than
    // joining the ESM config-files block above.
    files: [".dependency-cruiser.cjs"],
    extends: [js.configs.recommended],
    languageOptions: {
      sourceType: "commonjs",
      globals: globals.node,
    },
  },
  {
    // Hand-written ambient declaration files for their sibling scripts/*.mjs
    // and eslint-rules/*.mjs implementations (ts-json-schema-generator, the
    // coverage-thresholds helper, and require-stryker-rationale's own rule
    // module all need real types that JSDoc can't express cleanly in plain
    // .mjs). Pure type declarations, no runtime code -- same syntax-only
    // treatment as the root *.config.ts block below, and for the same
    // reason: not part of tsconfig.json's projectService-driven type
    // checking.
    files: ["scripts/**/*.d.mts", "eslint-rules/**/*.d.mts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
  },
  {
    // Root-level config files aren't part of tsconfig.json's `include` in
    // the same way source is, so these get syntax-only TS linting -- no
    // `projectService`, hence no type-aware rules -- rather than failing to
    // resolve a TS project.
    // (`*.config.ts` already matches `repo-contract.config.ts` -- no separate block for it).
    files: ["*.config.ts"],
    extends: [js.configs.recommended, ...tseslint.configs.recommended],
  },
  {
    // checks/**/*.ts holds the actual run/policy logic for each self-hosting
    // check (repo-contract.config.ts itself is just the assembly point), so
    // it gets the same type-aware strict linting src/ and scripts/ do.
    files: ["checks/**/*.ts"],
    extends: [
      js.configs.recommended,
      ...tseslint.configs.strictTypeChecked,
      ...tseslint.configs.stylisticTypeChecked,
    ],
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
    rules: {
      "@typescript-eslint/consistent-type-imports": "error",
      "@typescript-eslint/consistent-type-exports": "error",
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    // Preventive, across every type-aware layer: a `switch` over a union or
    // enum must handle every member or carry a `default`. Without it, adding a
    // member to `CheckStatus` / `OutputFormat` / a release-tag union leaves
    // existing switches silently falling through (the regression in
    // src/presets/shared/terminal-status.ts this was added for). Rules-only
    // block -- `languageOptions`/plugins are merged in from the type-aware
    // blocks above that already match these same globs.
    files: ["src/**/*.ts", "checks/**/*.ts", "scripts/**/*.ts", "test/**/*.ts"],
    rules: {
      "@typescript-eslint/switch-exhaustiveness-check": [
        "error",
        { considerDefaultExhaustiveForUnions: true },
      ],
    },
  },
  // Last on purpose -- turns off every core/stylistic rule that would
  // otherwise fight Prettier's own formatting decisions.
  eslintConfigPrettier,
)
