import type {
  ExceptionCategoryGroup,
  ExceptionPolicy,
  ExceptionPolicyConfig,
} from "../../src/helpers/index.js"

/**
 * Single source of truth for the repository's suppression-justification policy, imported by
 * checks/suppression-governance.ts's policy -- the same "one exported const, imported by the
 * script/check that gates on it" convention as scripts/coverage-thresholds.mjs (imported by both
 * scripts/report-coverage.mjs and checks/coverage.ts). There is no separate runtime config-merging
 * mechanism anywhere in repo-contract; a maintainer customizes this policy by editing this file
 * directly, exactly like coverage thresholds today.
 *
 * `justification`/`category`/`verificationMethod` are intentionally never auto-generated by the
 * check (see check.ts) -- when reconciliation scaffolds a new record it always starts with all
 * three at their empty value. A developer justifies a scaffolded record by editing those fields
 * directly in disable-comments.json:
 *   - `justification`: why this guardrail is deliberately bypassed for an approved reason, what
 *     alternatives were considered, and what was checked to confirm the finding is real. (This one
 *     prose field absorbed the older model's separate `alternatives`/`remediation` fields.)
 *   - `category`: what kind of suppression this is, from a fixed set (see evidence-types.ts's
 *     `SUPPRESSION_CATEGORIES`).
 *   - `verificationMethod`: how the claim above was substantiated, from a fixed set (see
 *     evidence-types.ts's `VERIFICATION_METHODS`).
 * The next run preserves those fields verbatim as long as the suppression's identity
 * (`suppression:<domain>:<rule>:<file>:<line>`) is still found. Moving a directive to a new line
 * makes its old record stale and scaffolds a fresh blank stub -- both fail the build until a human
 * carries the justification across; no move detection is attempted.
 *
 * `SuppressionPolicy`/`SuppressionDomainPolicy`/`SuppressionPolicyConfig` are thin aliases of
 * `repo-contract/helpers`'s classification-neutral `ExceptionPolicy`/`ExceptionCategoryGroup`/
 * `ExceptionPolicyConfig` (see specs/decisions/0013-reusable-exception-policy-helper.md) -- this
 * is the suppression-governance domain's own instantiation of that generic pattern: `group` is a
 * suppression's `domain` (`"eslint"`, `"typescript"`, `"stryker"`, ...), `category` is one of its
 * `rule` entries. Aliasing rather than redeclaring keeps this file's own literal `suppressionPolicy`
 * value assignable to the check's real resolver with no adapter code, at the cost of the
 * `requirements` array widening from the closed `SuppressionRequirement` union to a plain
 * `readonly string[]` at the type level -- `checks/suppression-governance.ts` recovers that
 * narrower check at runtime via `validateExceptionPolicyConfig(suppressionPolicy,
 * VALID_REQUIREMENTS)`, exactly as before this generalization.
 */

/**
 * One of the fixed, named fields a `SuppressionPolicy`'s `"exception"` mode can require.
 * `"justification"` is free-prose and hand-authored (it absorbed the older model's separate
 * `alternatives`/`remediation` prose). `"category"`/`"verificationMethod"` are hand-authored the
 * same way but are closed enumerations rather than free prose -- "filled in" means "one of a
 * fixed, reviewable set of classifications," not "some prose exists." `"reason"` is different in
 * kind: it's mechanically derived by a domain's own recognizer (recognizers.ts) from the directive
 * comment's own text and lives on the *finding*, not the record -- requiring it forces the author
 * to write inline rationale at the suppression site. Any domain may require any of these; today
 * only `stryker` requires `"reason"`.
 */
export type SuppressionRequirement = "justification" | "category" | "verificationMethod" | "reason"

/**
 * The three hand-authored record fields every non-`stryker` `"exception"` policy requires. (The
 * older model's `alternatives`/`remediation` prose folded into `justification`; the
 * `verifiedBy`/`verifiedContentHash` content-bound sign-off gate is deferred with the PR-approval
 * attestation work -- see specs/decisions/0013-reusable-exception-policy-helper.md's deferred-gaps
 * list.)
 */
const BASE_EXCEPTION_REQUIREMENTS: readonly SuppressionRequirement[] = [
  "justification",
  "category",
  "verificationMethod",
]

/** `BASE_EXCEPTION_REQUIREMENTS` plus `"reason"` -- the `stryker` domain additionally requires the mechanically-derived reason text on the finding. Derived, not re-listed, so the two can never silently diverge. */
const STRYKER_EXCEPTION_REQUIREMENTS: readonly SuppressionRequirement[] = [
  ...BASE_EXCEPTION_REQUIREMENTS,
  "reason",
]

/**
 * `"forbidden"`: the suppression is never permitted, regardless of justification.
 * `"allowed"`: the suppression is permitted unconditionally -- no justification required.
 * `"exception"`: the suppression is permitted only once every field named in `requirements` is a
 * non-empty string on the record.
 *
 * Deliberately not a numeric "how many details are required" threshold (the design this replaced)
 * -- a plain count is trivially satisfied by generating that many generic-sounding filler entries
 * without doing the underlying work. Naming exactly which fields must be filled in makes each one
 * individually reviewable against a specific question instead.
 *
 * An alias of `repo-contract/helpers`'s `ExceptionPolicy` -- see this file's own module doc
 * comment above for why aliasing rather than redeclaring.
 */
export type SuppressionPolicy = ExceptionPolicy

/**
 * `default` is this domain's fallback policy for any rule with no exact or pattern match in
 * `rules` (see `repo-contract/helpers`'s `resolveExceptionPolicy` for the full exact > pattern >
 * domain-default > global-default precedence -- generalized from what this repository originally
 * built here). Omit `default` to fall through to `GLOBAL_DEFAULT_POLICY` instead.
 *
 * An alias of `repo-contract/helpers`'s `ExceptionCategoryGroup`.
 */
export type SuppressionDomainPolicy = ExceptionCategoryGroup

/** An alias of `repo-contract/helpers`'s `ExceptionPolicyConfig`. */
export type SuppressionPolicyConfig = ExceptionPolicyConfig

/** Used when a suppression's `domain` has no entry in `suppressionPolicy` at all -- the strictest non-forbidding policy. Requires the three hand-authored record fields (not `reason`, which is a `stryker`-only mechanically-derived finding field). */
export const GLOBAL_DEFAULT_POLICY: SuppressionPolicy = {
  mode: "exception",
  requirements: BASE_EXCEPTION_REQUIREMENTS,
}

export const suppressionPolicy: SuppressionPolicyConfig = {
  eslint: {
    default: {
      mode: "exception",
      requirements: BASE_EXCEPTION_REQUIREMENTS,
    },
    rules: {
      "security/*": {
        mode: "forbidden",
      },
      "no-console": {
        mode: "allowed",
      },
      "react-hooks/exhaustive-deps": {
        mode: "exception",
        requirements: BASE_EXCEPTION_REQUIREMENTS,
      },
    },
  },

  typescript: {
    default: {
      mode: "exception",
      requirements: BASE_EXCEPTION_REQUIREMENTS,
    },
    rules: {
      "@ts-ignore": {
        mode: "forbidden",
      },
      // Whole-file type-checking opt-out -- strictly broader than `@ts-ignore`,
      // which is already forbidden, so this is too.
      "@ts-nocheck": {
        mode: "forbidden",
      },
      "@ts-expect-error": {
        mode: "allowed",
      },
    },
  },

  stryker: {
    default: {
      mode: "exception",
      requirements: STRYKER_EXCEPTION_REQUIREMENTS,
    },
    rules: {
      // Stryker's own literal "disable all mutators" token, not a glob -- see
      // recognizers.ts's `STRYKER_DIRECTIVE` comment for why this must stay an exact string
      // ("all"), never "*", to avoid accidentally glob-matching every real mutator name here.
      all: {
        mode: "forbidden",
      },
    },
  },
}
