/**
 * Single source of truth for the repository's suppression-justification policy, imported by
 * checks/suppression-governance.ts's policy -- the same "one exported const, imported by the
 * script/check that gates on it" convention as scripts/coverage-thresholds.mjs (imported by both
 * scripts/report-coverage.mjs and checks/coverage.ts). There is no separate runtime config-merging
 * mechanism anywhere in repo-contract; a maintainer customizes this policy by editing this file
 * directly, exactly like coverage thresholds today.
 *
 * `justification`/`alternatives`/`remediation`/`category`/`verificationMethod` are intentionally
 * never auto-generated by the check (see check.ts) -- when synchronization creates a new record,
 * it always starts with all five as empty strings. A developer justifies an auto-created record by
 * editing those five fields directly in disable-comments.json:
 *   - `justification`: why this is the best option.
 *   - `alternatives`: another way this could have been accomplished without disabling the rule.
 *   - `remediation`: what has already been attempted, and why -- despite that attempt -- disabling
 *     the rule still results in a better outcome than the alternatives.
 *   - `category`: what kind of suppression this is, from a fixed set (see evidence-types.ts's
 *     `SUPPRESSION_CATEGORIES`).
 *   - `verificationMethod`: how the claim above was substantiated, from a fixed set (see
 *     evidence-types.ts's `VERIFICATION_METHODS`).
 * The next run preserves those fields verbatim as long as the suppression's identity is still
 * found (unchanged, or moved unambiguously -- see synchronize.ts).
 */

/**
 * One of the fixed, named fields a `SuppressionPolicy`'s `"exception"` mode can require.
 * `"justification"`/`"alternatives"`/`"remediation"` are free-prose and hand-authored (see
 * evidence-types.ts's `DisableCommentRecord` doc comment). `"category"`/`"verificationMethod"` are
 * hand-authored the same way and at the same time, but are closed enumerations rather than free
 * prose -- "filled in" means "one of a fixed, reviewable set of classifications," not "some prose
 * exists." `"reason"` is different in kind from all four: it's mechanically derived by a domain's
 * own recognizer (recognizers.ts) from the directive comment's own text, so requiring it costs a
 * suppression's author nothing extra to fill in later -- the reason has to already be written,
 * inline, at the point the suppression is introduced. Any domain may require any of these; today
 * only `stryker` requires `"reason"`.
 */
export type SuppressionRequirement =
  "justification" | "alternatives" | "remediation" | "category" | "verificationMethod" | "reason"

/**
 * `"forbidden"`: the suppression is never permitted, regardless of justification.
 * `"allowed"`: the suppression is permitted unconditionally -- no justification required.
 * `"exception"`: the suppression is permitted only once every field named in `requirements` is a
 * non-empty string on the record.
 *
 * Deliberately not a numeric "how many details are required" threshold (the design this replaced)
 * -- a plain count is trivially satisfied by generating that many generic-sounding filler entries
 * without doing the underlying work. Naming exactly which fields must be filled in makes each one
 * individually reviewable against a specific question instead.
 */
export type SuppressionPolicy =
  | { readonly mode: "forbidden" }
  | { readonly mode: "allowed" }
  | {
      readonly mode: "exception"
      readonly requirements: readonly SuppressionRequirement[]
    }

/**
 * `default` is this domain's fallback policy for any rule with no exact or pattern match in
 * `rules` (see checks/suppression-governance.ts's `resolveRequirement` for the full exact >
 * pattern > domain-default > global-default precedence). Omit `default` to fall through to
 * `GLOBAL_DEFAULT_POLICY` instead.
 */
export interface SuppressionDomainPolicy {
  readonly default?: SuppressionPolicy
  readonly rules?: Readonly<Record<string, SuppressionPolicy>>
}

export type SuppressionPolicyConfig = Readonly<Record<string, SuppressionDomainPolicy>>

/** Used when a suppression's `domain` has no entry in `suppressionPolicy` at all -- the strictest non-forbidding policy, requiring every field. */
export const GLOBAL_DEFAULT_POLICY: SuppressionPolicy = {
  mode: "exception",
  requirements: ["justification", "alternatives", "remediation", "category", "verificationMethod"],
}

export const suppressionPolicy: SuppressionPolicyConfig = {
  eslint: {
    default: {
      mode: "exception",
      requirements: [
        "justification",
        "alternatives",
        "remediation",
        "category",
        "verificationMethod",
      ],
    },
    rules: {
      "security/*": {
        mode: "forbidden",
      },
      "no-console": {
        mode: "allowed",
      },
      "react-hooks/exhaustive-deps": {
        mode: "exception",
        requirements: [
          "justification",
          "alternatives",
          "remediation",
          "category",
          "verificationMethod",
        ],
      },
    },
  },

  typescript: {
    default: {
      mode: "exception",
      requirements: [
        "justification",
        "alternatives",
        "remediation",
        "category",
        "verificationMethod",
      ],
    },
    rules: {
      "@ts-ignore": {
        mode: "forbidden",
      },
      "@ts-expect-error": {
        mode: "allowed",
      },
    },
  },

  stryker: {
    default: {
      mode: "exception",
      requirements: [
        "justification",
        "alternatives",
        "remediation",
        "category",
        "verificationMethod",
        "reason",
      ],
    },
    rules: {
      // Stryker's own literal "disable all mutators" token, not a glob -- see
      // recognizers.ts's `STRYKER_DIRECTIVE` comment for why this must stay an exact string
      // ("all"), never "*", to avoid accidentally glob-matching every real mutator name here.
      all: {
        mode: "forbidden",
      },
    },
  },
}
